# Generated by Django 4.2.4 on 2023-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auctions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FSH", "Fashion"),
                            ("BVR", "Beverages"),
                            ("MDA", "Media"),
                            ("ELC", "Electronics"),
                            ("FOD", "Food"),
                            ("FNT", "Furniture"),
                        ],
                        default="FSH",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
