# Generated by Django 4.2.4 on 2023-12-14 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auctions"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctions",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auctions",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="auctions",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="auctions",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctions",
            name="title",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="auctions",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOD", "Food"),
                    ("FSH", "Fashion"),
                    ("ELC", "Electronics"),
                    ("FNT", "Furniture"),
                    ("BVR", "Beverages"),
                    ("MDA", "Media"),
                ],
                default="FSH",
                max_length=3,
            ),
        ),
    ]
