# Generated by Django 4.2.4 on 2023-12-14 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_auctions_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BVR", "Beverages"),
                            ("ELC", "Electronics"),
                            ("MDA", "Media"),
                            ("FNT", "Furniture"),
                            ("FOD", "Food"),
                            ("FSH", "Fashion"),
                        ],
                        default="FSH",
                        max_length=3,
                    ),
                ),
                ("title", models.CharField(default="", max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("image", models.URLField(blank=True)),
                ("date", models.DateField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Auctions",
        ),
    ]
