# Generated by Django 4.2.4 on 2023-12-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_auction_category_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELC", "Electronics"),
                    ("MDA", "Media"),
                    ("BVR", "Beverages"),
                    ("FOD", "Food"),
                    ("FNT", "Furniture"),
                    ("FSH", "Fashion"),
                ],
                default="FSH",
                max_length=3,
            ),
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="item",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="item",
            field=models.ManyToManyField(related_name="item", to="auctions.auction"),
        ),
    ]
