# Generated by Django 4.2.4 on 2023-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_alter_auction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                choices=[
                    ("MDA", "Media"),
                    ("FNT", "Furniture"),
                    ("FOD", "Food"),
                    ("FSH", "Fashion"),
                    ("ELC", "Electronics"),
                    ("BVR", "Beverages"),
                ],
                default="FSH",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
