# Generated by Django 4.2.4 on 2024-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0019_alter_auction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                choices=[
                    ("FNT", "Furniture"),
                    ("MDA", "Media"),
                    ("BVR", "Beverages"),
                    ("FSH", "Fashion"),
                    ("ELC", "Electronics"),
                    ("FOD", "Food"),
                ],
                default="FSH",
                max_length=3,
            ),
        ),
    ]
