# Generated by Django 4.2.4 on 2024-01-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0023_alter_auction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                choices=[
                    ("MDA", "Media"),
                    ("FSH", "Fashion"),
                    ("FOD", "Food"),
                    ("FNT", "Furniture"),
                    ("BVR", "Beverages"),
                    ("ELC", "Electronics"),
                ],
                default="FSH",
                max_length=3,
            ),
        ),
    ]
