# Generated by Django 4.2.4 on 2024-01-18 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0024_auction_closed_alter_auction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOD", "Food"),
                    ("ELC", "Electronics"),
                    ("MDA", "Media"),
                    ("FNT", "Furniture"),
                    ("FSH", "Fashion"),
                    ("BVR", "Beverages"),
                ],
                default="FSH",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="Closed_Deals",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("deal_price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("date", models.DateField(auto_now=True)),
                (
                    "deal_buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_product",
                        to="auctions.auction",
                    ),
                ),
                (
                    "deal_seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
